name: mamanotes
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_svg: ^2.0.5
  flutter_screenutil: ^5.7.0
  google_fonts: ^4.0.3
  font_awesome_flutter: ^10.4.0
  flutter_timeline: ^0.3.0
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.5.3
  firebase_storage: ^11.1.2
  image_picker: ^0.8.7+4
  google_sign_in: ^6.1.0
  intl: ^0.17.0
  cached_network_image: ^3.2.3
  collection: ^1.15.0
  firebase_cached_image: ^0.4.2

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#FFCDD7"
  image: assets/images/logo2.png
  android_12:
    image: assets/images/logo2.png
    color: "#FFCDD7"




